
drop table if exists temp.TempMomentIllustrations;

create temp table temp.TempMomentIllustrations(ExistingName text);

insert into temp.TempMomentIllustrations (ExistingName)
values
-- Governors
	('Moment_PromoteGovernor_Ambassador.dds')
	,('Moment_PromoteGovernor_Builder.dds')
	,('Moment_PromoteGovernor_Cardinal.dds')
	,('Moment_PromoteGovernor_Defender.dds')
	,('Moment_PromoteGovernor_Educator.dds')
	,('Moment_PromoteGovernor_Merchant.dds')
	,('Moment_PromoteGovernor_ResourceManager.dds')
	,('MomentXP2_PromoteGovernor_GrandVizier.dds')
-- Natural Wonders
	,('Moment_Naturalwonder_BarrierReef.dds')
	,('Moment_NaturalWonder_CliffsOfDover.dds')
	,('Moment_Naturalwonder_CraterLake.dds')
	,('Moment_NaturalWonder_DeadSea.dds')
	,('Moment_NaturalWonder_Everest.dds')
	,('Moment_NaturalWonder_Galapagos.dds')
	,('Moment_NaturalWonder_Kilimanjaro.dds')
	,('Moment_NaturalWonder_Pantanal.dds')
	,('Moment_NaturalWonder_Piopiotahi.dds')
	,('Moment_NaturalWonder_Torres.dds')
	,('Moment_NaturalWonder_Tsingy.dds')
	,('Moment_NaturalWonder_Yosemite.dds')
	,('Moment_NaturalWonder_Ubsunur.dds')
	,('Moment_NaturalWonder_Zhangye.dds')
	,('Moment_NaturalWonder_Roraima.dds')
	,('Moment_NaturalWonder_Matterhorn.dds')
	,('Moment_Naturalwonder_Retba.dds')
	,('Moment_NaturalWonder_EyeoftheSahara.dds')
	,('Moment_NaturalWonder_DelicateArch.dds')
	,('Moment_Naturalwonder_Lyseford.dds')
	,('Moment_Naturalwonder_GiantsCauseway.dds')
	,('Moment_NaturalWonder_Eyjafjallajokull.dds')
	,('Moment_Naturalwonder_HaLongBay.dds')
	,('Moment_Naturalwonder_Uluru.dds')
	,('MomentXP2_FindingChocolateHills.dds')
	,('MomentXP2_FindingDevilsTower.dds')
	,('MomentXP2_FindingGobustan.dds')
	,('MomentXP2_FindingIkKil.dds')
	,('MomentXP2_FindingPamukkale.dds')
	,('MomentXP2_FindingVesuvius.dds')
	,('MomentXP2_FindingWhiteDesert.dds')
-- Complete Tech
	,('Moment_CompleteTech_Information.dds')
	,('Moment_CompleteTech_Medieval.dds')
	,('Moment_CompleteTech_Renaissance.dds')
	,('Moment_CompleteTech_Industrial.dds')
	,('Moment_CompleteTech_Modern.dds')
	,('Moment_CompleteTech_Classical.dds')
	,('Moment_CompleteTech_Atomic.dds')
-- Complete Civic
	,('Moment_CompleteCivicInformation.dds')
	,('Moment_CompleteCivicMedieval.dds')
	,('Moment_CompleteCivicRenaissance.dds')
	,('Moment_CompleteCivicIndustrial.dds')
	,('Moment_CompleteCivicModern.dds')
	,('MomentXP2_CompleteCivic_Future.dds')
	,('Moment_CompleteCivicClassical.dds')
	,('Moment_CompleteCivicAtomic.dds')
	,('MomentXP2_CompleteFirstFutureEraTech.dds')
-- Buildings
	,('MomentXP2_BuildingTheOpenAirMuseum.dds')
	,('MomentXP2_BuildingIceHockeyRink.dds')
	,('MomentXP2_BuildingTheTerraceFarm.dds')
	,('MomentXP2_BuildingThePa.dds')
	,('MomentXP2_BuildingTheQhapaqNan.dds')
	,('MomentXP2_BuildingTheGrandBazaar.dds')
	,('MomentXP2_BuildingTheMarae.dds')
	,('MomentXP2_BuildingBiblioteque.dds')
	,('MomentXP2_BuildingTheThermalBath.dds')
	,('MomentXP2_BuildingTheCothon.dds')
	,('MomentXP2_BuildingSuguba.dds')
-- Infrastructure
	,('Moment_Infrastructure_Scotland.dds')
	,('Moment_Infrastructure_Netherlands.dds')
	,('Moment_Infrastructure_Mapuche.dds')
	,('Moment_Infrastructure_Cree.dds')
	,('Moment_Infrastructure_Australia.dds')
	,('Moment_Infrastructure_Persia.dds')
	,('Moment_Infrastructure_Nubia.dds')
	,('Moment_Infrastructure_Indonesia.dds')
	,('Moment_Infrastructure_Macedon.dds')
	,('Moment_Infrastructure_Japan.dds')
	,('Moment_Infrastructure_America.dds')
	,('Moment_Infrastructure_Arabia.dds')
	,('Moment_Infrastructure_Mongolia.dds')
	,('Moment_Infrastructure_Khmer.dds')
	,('Moment_Infrastructure_Norway.dds')
	,('Moment_Infrastructure_Poland.dds')
	,('Moment_Infrastructure_Aztec.dds')
	,('Moment_Infrastructure_Georgia.dds')
	,('Moment_Infrastructure_Greece.dds')
	,('Moment_Infrastructure_Rome.dds')
	,('Moment_Infrastructure_Germany.dds')
	,('Moment_Infrastructure_Zulu.dds')
	,('Moment_Infrastructure_Russia.dds')
	,('Moment_Infrastructure_Kongo.dds')
	,('Moment_Infrastructure_England.dds')
	,('Moment_Infrastructure_Korea.dds')
	,('Moment_Infrastructure_Brazil.dds')
	,('Moment_Infrastructure_China.dds')
	,('Moment_Infrastructure_Egypt.dds')
	,('Moment_Infrastructure_France.dds')
	,('Moment_Infrastructure_India.dds')
	,('Moment_Infrastructure_Scythia.dds')
	,('Moment_Infrastructure_Spanish.dds')
	,('Moment_Infrastructure_Ziggurat.dds')
-- Firsts
	,('Moment_FirstAirUnitEarlyGame.dds')
	,('Moment_FirstAirUnitLateGame.dds')
	,('Moment_FirstSeaUnitEarly.dds')
	,('Moment_FirstSeaUnitMid.dds')
-- Unique Units
	,('Moment_UniqueUnit_America_Mustang.dds')
	,('Moment_UniqueUnit_America_Roughrider.dds')
	,('Moment_UniqueUnit_Arab.dds')
	,('Moment_UniqueUnit_Aztec.dds')
	,('Moment_UniqueUnit_Brazil.dds')
	,('Moment_UniqueUnit_China.dds')
	,('Moment_UniqueUnit_Cree.dds')
	,('Moment_UniqueUnit_Netherlands.dds')
	,('Moment_UniqueUnit_Australia.dds')
	,('Moment_UniqueUnit_Egypt.dds')
	,('Moment_UniqueUnit_England_Redcoats.dds')
	,('Moment_UniqueUnit_England_Seadog.dds')
	,('Moment_UniqueUnit_France_GardeImperiale.dds')
	,('Moment_UniqueUnit_Georgia.dds')
	,('Moment_UniqueUnit_Germany_UBoat.dds')
	,('Moment_UniqueUnit_Greece.dds')
	,('Moment_UniqueUnit_India.dds')
	,('Moment_UniqueUnit_Indonesia.dds')
	,('Moment_UniqueUnit_Japan.dds')
	,('Moment_UniqueUnit_Khmer.dds')
	,('Moment_UniqueUnit_Konga.dds')
	,('Moment_UniqueUnit_Macedon_Hetairoi.dds')
	,('Moment_UniqueUnit_Macedon_Hypaspist.dds')
	,('Moment_UniqueUnit_Mapuche.dds')
	,('Moment_UniqueUnit_Mongolia.dds')
	,('Moment_UniqueUnit_Norway_Berserker.dds')
	,('Moment_UniqueUnit_Norway_Longship.dds')
	,('Moment_UniqueUnit_Nubia.dds')
	,('Moment_UniqueUnit_Persia.dds')
	,('Moment_UniqueUnit_Poland.dds')
	,('Moment_UniqueUnit_Rome.dds')
	,('Moment_UniqueUnit_Russia.dds')
	,('Moment_UniqueUnit_Scotland.dds')
	,('Moment_UniqueUnit_Scythia.dds')
	,('Moment_UniqueUnit_Spain.dds')
	,('Moment_UniqueUnit_Sumerian.dds')
	,('Moment_UniqueUnit_Zulu.dds')
	,('MomentXP2_TrainingJanissary.dds')
	,('MomentXP2_TrainingCarolean.dds')
	,('MomentXP2_TrainingBarbaryCorsair.dds')
	,('MomentXP2_TrainingMountie.dds')
	,('MomentXP2_Training_BlackArmy.dds')
	,('MomentXP2_TrainingHuzar.dds')
	,('MomentXP2_TrainingWarakaq.dds')
	,('MomentXP2_TrainingMadekalu.dds')
	,('MomentXP2_Training_Toa.dds')
	,('MomentXP2_TrainingBireme.dds')
-- Governments
	,('Moment_Government_Autocracy.dds')
	,('Moment_Government_Oligarchy.dds')
	,('Moment_Government_ClassicalRepublic.dds')
	,('Moment_Government_Monarchy.dds')
	,('Moment_Government_Theocracy.dds')
	,('Moment_Government_Merchant.dds')
	,('Moment_Government_Fascism.dds')
	,('Moment_Government_Communism.dds')
	,('Moment_Government_Democracy.dds')
	,('MomentXP2_Government_CorpLibertarianism.dds')
	,('MomentXP2_Government_SyntheticTechnocracy.dds')
	,('MomentXP2_Gorvernment_DigitalDemocracy.dds')
-- Eras
	,('Moment_EraEntry_Ancient.dds')
	,('Moment_EraEntry_Classical.dds')
	,('Moment_EraEntry_Medieval.dds')
	,('Moment_EraEntry_Renaissance.dds')
	,('Moment_EraEntry_Industrial.dds')
	,('Moment_EraEntry_Modern.dds')
	,('Moment_EraEntry_Atomic.dds')
	,('Moment_EraEntry_Information.dds')
	,('MomentXP2_EnterFutureEra.dds')
	,('MomentXP2_EnterFutureEra.dds')
-- STK (Frontier Pass)
	,('MomentSTK_BermudaTriangle.dds')
	,('MomentSTK_ComandanteGeneral.dds')
	,('MomentSTK_FountainOfYouth.dds')
	,('MomentSTK_Hacienda.dds')
	,('MomentSTK_Hulche.dds')
	,('MomentSTK_Llanero.dds')
	,('MomentSTK_Observatory.dds')
	,('MomentSTK_Paititi.dds')
	,('MomentSTK_RockHewnChurch.dds')
	,('MomentSTK_OromoCavalry.dds')
	,('MomentSTK_DromonShip.dds')
	,('MomentSTK_Hippodrome.dds')
	,('MomentSTK_Oppidum.dds')
	,('MomentSTK_Tagma.dds')
	,('MomentSTK_Sabum.dds')
	,('MomentSTK_Palgum.dds')
	,('MomentSTK_Thanh.dds')
	,('MomentSTK_VoiChien.dds');

update MomentIllustrations
set Texture = 'CHM_' || Texture
where Texture in (
	select ExistingName from temp.TempMomentIllustrations
);

drop table if exists temp.TempMomentIllustrations;